// ruleset.js — the canonical GPFS POC Lane signal set.
// AUTO-GENERATED from the reconciled governance ruleset, then hand-curated.
// Each signal carries detection patterns plus how it maps to the policy.
// Patterns are matched case-insensitively against file paths and contents.

export const SIGNALS = [
  {
    id: "runtime-ai-direct-vendor-host",
    label: "Direct runtime call to a public LLM vendor API host",
    why: "Section 5.5 explicitly disqualifies Lane 1 for direct calls to api.anthropic.com / api.openai.com etc. A request to a vendor inference host is a runtime AI model call that is NOT the approved enterprise proxy, so it fails 5.5 -> Lane 2. It is also an outbound network call (5.6). A call is 'direct' (disqualifying) unless its URL is a same-origin/relative approved proxy path (see approved-enterprise-proxy).",
    mapsTo: "5.5",
    effect: "fails-lane1-condition",
    confidence: "strong",
    patterns: ["api\\.anthropic\\.com", "api\\.openai\\.com", "[a-z0-9-]+\\.openai\\.azure\\.com", "openai\\.azure\\.com", "generativelanguage\\.googleapis\\.com", "api\\.cohere\\.(ai|com)", "api\\.mistral\\.ai", "api\\.groq\\.com", "api-inference\\.huggingface\\.co", "api\\.replicate\\.com", "bedrock(-runtime)?\\.[a-z0-9-]+\\.amazonaws\\.com", "baseURL\\s*[:=]\\s*['\"`]https?://"],
  },
  {
    id: "runtime-ai-vendor-sdk-import",
    label: "Embedded model SDK imported / instantiated at runtime",
    why: "Section 5.5 names 'embedded model SDKs with client-side keys' as NOT qualifying. Importing and instantiating a vendor model SDK in shipped runtime code is a runtime AI call outside the approved proxy -> fails 5.5 -> Lane 2. Strongest when paired with a client-side key. Scope to runtime entrypoints; a bare entry in devDependencies / build scripts / node_modules / tests / docs does NOT set the lane (build-tool provenance is irrelevant).",
    mapsTo: "5.5",
    effect: "fails-lane1-condition",
    confidence: "strong",
    patterns: ["@anthropic-ai/sdk", "import\\s+.*Anthropic", "new\\s+Anthropic\\s*\\(", "['\"]openai['\"]", "new\\s+OpenAI\\s*\\(", "@azure/openai", "AzureOpenAI", "@google/generative-ai", "GoogleGenerativeAI\\s*\\(", "@google-cloud/aiplatform", "cohere-ai", "CohereClient\\s*\\(", "@mistralai/mistralai", "@huggingface/inference", "@xenova/transformers", "['\"]replicate['\"]", "['\"]ollama['\"]", "langchain", "@langchain/", "llama-?index", "@aws-sdk/client-bedrock", "require\\(['\"](openai|@anthropic-ai/sdk|@google/generative-ai|cohere-ai|@mistralai/mistralai)['\"]\\)", "from\\s+openai\\s+import", "import\\s+openai\\b", "from\\s+anthropic\\s+import", "import\\s+anthropic\\b", "from\\s+cohere\\s+import", "import\\s+google\\.generativeai", "\\bOpenAI\\s*\\(", "\\bAsyncOpenAI\\s*\\("],
  },
  {
    id: "client-side-model-api-key",
    label: "Client-side / hardcoded model provider API key",
    why: "Section 5.5 specifically disqualifies 'client-side keys'. A vendor key shipped in client code, .env, or bundled via a public env prefix (VITE_/NEXT_PUBLIC_/REACT_APP_) confirms the AI call is direct, not via the keyless enterprise proxy. Also a secrets-exposure red flag. A bare server-only key (e.g. OPENAI_API_KEY read in a server route) is server-side -> still implies Lane 2, but via backend presence rather than client-key exposure.",
    mapsTo: "5.5",
    effect: "fails-lane1-condition",
    confidence: "strong",
    patterns: ["sk-ant-[A-Za-z0-9_-]{20,}", "sk-proj-[A-Za-z0-9_-]{20,}", "sk-[A-Za-z0-9]{20,}", "AIza[0-9A-Za-z_-]{30,}", "(VITE_|NEXT_PUBLIC_|REACT_APP_|PUBLIC_)[A-Z_]*(OPENAI|ANTHROPIC|GEMINI|COHERE|MISTRAL|AI|LLM)[A-Z_]*_?(API_)?KEY", "(OPENAI|ANTHROPIC|GEMINI|COHERE|MISTRAL)_API_KEY", "dangerouslyAllowBrowser\\s*:\\s*true"],
  },
  {
    id: "approved-enterprise-proxy",
    label: "Runtime AI call routed through approved enterprise proxy on General data (5.5 exception)",
    why: "Section 5.5 carves out an exception: a runtime AI call to an approved enterprise endpoint (e.g. the platform /api/chat proxy) on General data IS allowed in Lane 1. The proxy is keyless from the client. This is the ONLY AI-call shape compatible with Lane 1. Holds ONLY if data scope is General (5.2, user-confirmed) AND no direct vendor host/SDK/key co-occurs. Fragile to spoofing: a same-origin /api/chat that an app's OWN backend forwards to a vendor with a server-side key is still effectively direct AND triggers backend-server-present; net effect remains Lane 2, so precedence holds.",
    mapsTo: "5.5",
    effect: "context-needed",
    confidence: "moderate",
    patterns: ["fetch\\(\\s*['\"`]/api/chat", "['\"`]/api/(ai|llm|completion|chat)\\b", "fetch\\(\\s*['\"`]/api/", "['\"`]https?://tools\\.gpfundsolutions\\.com/api/", "/api/proxy/(chat|llm)"],
  },
  {
    id: "backend-server-present",
    label: "Backend / server runtime present",
    why: "Section 6: a utility enters Lane 2 when it needs a backend, integration, authentication, or live data connection. A server process (Express/Flask/FastAPI/Nest/Next API routes/serverless functions) is not a static 'host as-is' Lane 1 file. NOTE: the presence of an /api proxy path alone is the 5.5 exception, not automatically Lane 2 \u2014 weigh server presence together with writes/DB/integration signals. If the backend itself makes direct vendor calls, that is the real Lane 2 trigger.",
    mapsTo: "backend-needed",
    effect: "context-needed",
    confidence: "moderate",
    patterns: ["import\\s+express|require\\(['\"]express['\"]\\)|['\"]express['\"]\\s*:", "fastify|@nestjs/|koa", "from\\s+flask\\s+import|Flask\\(__name__\\)", "from\\s+fastapi\\s+import|FastAPI\\s*\\(", "app\\.listen\\s*\\(", "http\\.createServer|createServer\\s*\\(", "app\\.(get|post|put|delete)\\s*\\(", "pages/api/.*\\.(js|ts)$", "app/api/.*/route\\.(js|ts)$", "(^|/)(server|app|main)\\.(js|ts|py)$", "(^|/)Dockerfile$", "docker-compose\\.ya?ml$", "(^|/)Procfile$", "netlify/functions/", "functions/.*\\.(js|ts)$"],
  },
  {
    id: "db-source-of-truth-write",
    label: "Write to a database / source-of-truth / production system",
    why: "Section 5.3 requires NO writes to any source of truth or production system. A DB write client, ORM persist call, mutating SQL, or mutating HTTP verb to a backend is concrete write evidence -> fails 5.3 -> Lane 2. If the target is a confirmed system of record (e.g. investor ledger), it ALSO pushes the tier to APPROVE. Reads are fine; distinguish reads from writes. Whether the target is a true source of truth vs a scratch/demo store needs user confirmation.",
    mapsTo: "5.3",
    effect: "fails-lane1-condition",
    confidence: "moderate",
    patterns: ["INSERT\\s+INTO", "UPDATE\\s+\\w+\\s+SET", "DELETE\\s+FROM", "UPSERT|MERGE\\s+INTO|CREATE\\s+TABLE|ALTER\\s+TABLE", "\\.(insert|update|upsert|delete|save|create|bulkCreate|findOneAndUpdate)\\s*\\(", "prisma\\.[a-zA-Z]+\\.(create|update|upsert|delete)", "method\\s*:\\s*['\"](POST|PUT|PATCH|DELETE)['\"]", "axios\\.(post|put|patch|delete)\\s*\\(", "(pg|mysql2?|sqlite3|mongodb|mongoose|psycopg2|sqlalchemy|knex|sequelize|@prisma/client)\\b", "createPool\\(|createConnection\\(|DATABASE_URL", "(postgres|postgresql|mysql|mongodb)://"],
  },
  {
    id: "backend-as-a-service-write",
    label: "Write/integration to a BaaS or external SaaS system of record",
    why: "Section 6 lists 'an integration' and 'a live data connection' as Lane 2 triggers. A BaaS datastore (Supabase/Firebase/Airtable/Dynamo/Cosmos) or a mutating call to a CRM/ticketing/accounting/document SaaS is a live data connection AND a write to a potential production source of truth (5.3), often Approve-state.",
    mapsTo: "5.3",
    effect: "fails-lane1-condition",
    confidence: "moderate",
    patterns: ["@supabase/supabase-js", "supabase\\.from\\([^)]*\\)\\.(insert|update|upsert|delete)", "firebase|getFirestore|@google-cloud/firestore", "@aws-sdk/client-dynamodb|@aws-sdk/client-s3|@azure/cosmos", "airtable", "graph\\.microsoft\\.com/v1\\.0/.*/items", "[a-z0-9-]+\\.salesforce\\.com/services|/services/data/", "api\\.hubapi\\.com", "api\\.atlassian\\.com|/rest/api/3/issue", "quickbooks\\.api\\.intuit\\.com", "slack\\.com/api/(chat\\.postMessage|files\\.upload)", "docusign|esignature"],
  },
  {
    id: "third-party-cdn-script",
    label: "Un-allowlisted third-party <script src> from external CDN",
    why: "Section 5.6 forbids un-allowlisted third-party scripts and gives 'external <script src> from a random CDN' as the exact example. A remote script tag (or dynamic remote import / importScripts) loads uncontrolled code into the SSO-fronted page -> fails 5.6 unless the host is on the approved allowlist (which code analysis cannot confirm). Bias toward flag; common public CDNs are concrete hits.",
    mapsTo: "5.6",
    effect: "fails-lane1-condition",
    confidence: "moderate",
    patterns: ["<script[^>]+src=['\"]https?://(?!([a-z0-9.-]*\\.)?gpfundsolutions\\.com)", "<link[^>]+href=['\"]https?://(?!([a-z0-9.-]*\\.)?gpfundsolutions\\.com)", "cdn\\.jsdelivr\\.net", "unpkg\\.com", "cdnjs\\.cloudflare\\.com", "ajax\\.googleapis\\.com", "code\\.jquery\\.com", "cdn\\.tailwindcss\\.com", "cdn\\.skypack\\.dev|esm\\.sh", "stackpath\\.bootstrapcdn\\.com", "import\\(\\s*['\"]https?://", "document\\.createElement\\(['\"]script['\"]\\)"],
  },
  {
    id: "third-party-analytics-telemetry",
    label: "Third-party analytics / telemetry / tag-manager beacon",
    why: "Analytics, error-telemetry, and tag-manager snippets are BOTH un-allowlisted third-party scripts (5.6) AND outbound network calls that exfiltrate usage data (5.6). Common in scaffolds and easy to miss. They fail 5.6 -> Lane 2 unless the host is on the approved allowlist.",
    mapsTo: "5.6",
    effect: "fails-lane1-condition",
    confidence: "strong",
    patterns: ["www\\.googletagmanager\\.com|gtag\\s*\\(", "www\\.google-analytics\\.com", "connect\\.facebook\\.net", "js\\.sentry-cdn\\.com|@sentry/browser|Sentry\\.init", "cdn\\.segment\\.com|analytics\\.(track|identify)\\(", "static\\.hotjar\\.com|hotjar", "js\\.posthog\\.com|posthog\\.init", "plausible\\.io/js", "mixpanel|amplitude"],
  },
  {
    id: "outbound-network-call-nonallowlisted",
    label: "Outbound network call to a non-allowlisted external host",
    why: "Section 5.6 allows NO outbound network calls except an approved allowlist. Any fetch/axios/XHR/WebSocket/EventSource/sendBeacon/Image to an absolute external host that is not same-origin and not allowlisted is a candidate violation. Same-origin/relative calls do not trip this. The allowlist is environment/config-defined, so the analyzer surfaces the host list for confirmation rather than auto-failing. NOTE for THIS analyzer: api.github.com / raw.githubusercontent.com is the validator's own allowlisted dependency (it is how a repo URL is fetched) and must NOT be reported as a violation of the utility under test.",
    mapsTo: "5.6",
    effect: "context-needed",
    confidence: "moderate",
    patterns: ["fetch\\(\\s*['\"`]https?://", "axios\\.(get|post|put|patch|delete|request)\\(\\s*['\"`]https?://", "new\\s+WebSocket\\(\\s*['\"`]wss?://", "new\\s+EventSource\\(\\s*['\"`]https?://", "navigator\\.sendBeacon\\s*\\(", "XMLHttpRequest|\\.open\\(\\s*['\"`](GET|POST)", "baseURL\\s*:\\s*['\"`]https?://(?!([a-z0-9.-]*\\.)?gpfundsolutions\\.com)"],
  },
  {
    id: "sso-gating-posture",
    label: "GPFS SSO gating posture (absence usually fine; explicit public/consumer-auth is a flag)",
    why: "Section 5.6 requires the utility runs behind GPFS SSO. Lane 1 Shared Hosting (tools.gpfundsolutions.com) supplies SSO at the platform layer, so ABSENCE of in-app auth is NOT disqualifying by itself. Only an explicit anonymous/public-access config, or a self-rolled consumer auth provider that bypasses GPFS SSO, contradicts 5.6. Final SSO placement is a hosting fact (context-needed).",
    mapsTo: "5.6",
    effect: "context-needed",
    confidence: "weak",
    patterns: ["@azure/msal|msal|entra|openid|oidc|saml", "allowAnonymous\\s*:\\s*true|requireAuth\\s*:\\s*false|public\\s*:\\s*true|auth\\s*:\\s*['\"]none['\"]", "auth0|@clerk|firebase/auth|supabase\\.auth\\.signUp|next-auth\\s+Providers\\.Google", "createUserWithEmailAndPassword|signUp\\("],
  },
  {
    id: "client-persistence-sensitive",
    label: "Client-side persistence (localStorage/IndexedDB/cookies/FS) of potentially sensitive data",
    why: "Section 5.7 forbids local persistence of Client/Fund or Restricted data. Code can detect THAT persistence happens; it cannot determine whether the stored payload is sensitive. So persistence alone is context-needed \u2014 it fails 5.7 only if the persisted data is sensitive (correlate with data-scope-restricted-keywords; user-confirmed).",
    mapsTo: "5.7",
    effect: "context-needed",
    confidence: "moderate",
    patterns: ["localStorage\\.setItem|window\\.localStorage", "sessionStorage\\.setItem", "indexedDB\\.open|\\bidb\\b|new\\s+Dexie\\(|PouchDB\\(", "document\\.cookie\\s*=", "caches\\.open\\(|navigator\\.storage|FileSystemWritableFileStream", "localforage", "fs\\.(writeFile|writeFileSync|appendFile)"],
  },
  {
    id: "data-scope-restricted-keywords",
    label: "Client / Fund / Restricted data-scope keywords present",
    why: "STAR 3.1: touching Client/Fund or Restricted data is an APPROVE-state trigger (forces Lane 2) AND violates 5.2 (General data only) and, if persisted, 5.7. Keywords are a HINT only \u2014 a variable named 'client' may be an HTTP client, a fixture named 'client_demo.json' may be synthetic. Code cannot confirm real sensitivity; the user must confirm scope. Default conservatively (provisional-Approve) on unresolved hits.",
    mapsTo: "5.2",
    effect: "context-needed",
    confidence: "weak",
    patterns: ["\\bclient(_|\\s)?(name|id|account|holding|portfolio)\\b", "\\bfund(_|\\s)?(name|id|nav|aum|position)\\b", "\\b(investor|LP|GP|capital\\s*account|capital\\s*call|NAV|AUM|subscription|redemption|portfolio|ledger)\\b", "\\b(SSN|EIN|TIN|account\\s*number|routing\\s*number|PII|PHI)\\b", "\\b(restricted|confidential|MNPI|material\\s*non[- ]public)\\b"],
  },
  {
    id: "data-scope-general-markers",
    label: "General / demo / sample data markers (supports USE + 5.2)",
    why: "Supports the USE tier and 5.2 (General data only). Explicit general/public/sample/demo/mock markers, with NO sensitive-scope keyword and NO source-of-truth write, reinforce Lane 1 eligibility. Informational only \u2014 biases toward Lane 1 but never decides.",
    mapsTo: "pattern-classification",
    effect: "informational",
    confidence: "weak",
    patterns: ["\\b(general|public|sample|demo|mock(Data)?|lorem|placeholder)\\b", "fixtures?/", "seed(Data)?|dummy"],
  },
  {
    id: "reliance-deliverable-markers",
    label: "Output relied on for client deliverable / reporting / reconciliation / control / compliance",
    why: "STAR 3.1: if output is relied on for a client deliverable, financial reporting, a reconciliation, a control, or compliance, it is APPROVE-state -> Lane 2 + Controlled Workflow Packet + AI Committee. Code can spot hints (report/statement/export-to-authoritative-format, reconciliation logic) but CANNOT determine who relies on the output \u2014 reliance is a human fact the user must confirm. An export existing does not prove reliance; its absence does not prove non-reliance.",
    mapsTo: "risk-tier-approve",
    effect: "context-needed",
    confidence: "weak",
    patterns: ["\\breconcil(e|iation)\\b|trial\\s*balance|general\\s*ledger|NAV\\s*pack", "(generate|build|export)\\w*(Report|Statement|Deliverable|Pack|Filing|Invoice|Summary)", "exportTo(Excel|Pdf|Csv)|jsPDF|pdfkit|exceljs|xlsx\\.write|docx|pptxgenjs", "\\b(compliance|audit|regulat(or|ory)|filing|disclosure|control\\s*report)\\b", "capital\\s*statement|investor\\s*report"],
  },
  {
    id: "reliance-shared-repeatable-register",
    label: "Shared / repeatable / multi-user markers (Register tier)",
    why: "STAR 3.1 Register applies when a utility is shared, repeatable, or relied on by anyone other than the builder. Register fails 5.1 (Lane 1 requires USE, or an AI-Operations-Lead-approved bounded Pilot) -> Lane 2. Multi-user auth/roles, scheduled jobs, exported CLI/library, or docs describing team use are code-visible hints; actual sharing/reliance is a human fact the user must confirm. Default toward Register over Use whenever non-builder reliance is plausible.",
    mapsTo: "risk-tier-register",
    effect: "context-needed",
    confidence: "weak",
    patterns: ["roles?\\s*[:=]|isAdmin|permissions?\\s*[:=]", "node-cron|cron\\.schedule\\(|@nestjs/schedule|crontab|schedule\\.", "\"bin\"\\s*:|#!/usr/bin/env\\s+node|argparse|click\\.command", "\\b(shared|team|everyone|colleagues|other\\s+users|multi[- ]user)\\b"],
  },
  {
    id: "logic-probabilistic-extraction-parsing",
    label: "Probabilistic extraction / parsing of documents (YELLOW)",
    why: "Common-patterns guide: extraction/parsing is YELLOW and maps to Lane 2/Register because it is probabilistic by nature and errors are silent. Sets LOGIC POSTURE = YELLOW; under 5.4 it stays Lane 1 only with 100% human review of every output before use, and probabilistic output relied on by anyone raises the tier. Pure deterministic regex parsing of a fixed format is GREEN-leaning; freeform/LLM/OCR extraction is YELLOW.",
    mapsTo: "logic-yellow",
    effect: "raises-tier",
    confidence: "moderate",
    patterns: ["pdf-parse|pdfjs|pdf2json|pdfplumber|@azure/ai-form-recognizer|textract", "tesseract|ocr\\(|OCR", "\\bmammoth\\b|\\bcheerio\\b", "extract\\w*\\(|parse(Document|Pdf|Resume|Invoice)|extractFields|extractEntities", "named.?entit|(extract|pull|scrape)\\s+(fields|data|values)\\s+from"],
  },
  {
    id: "logic-probabilistic-qa-retrieval",
    label: "Document Q&A / retrieval / RAG (YELLOW-RED)",
    why: "Common-patterns guide: Document Q&A/retrieval is YELLOW-RED and ALWAYS Lane 2/Register because answer accuracy is relied on. Vector store + retrieval-then-answer is a strong Lane 2 indicator and raises the tier when relied upon. Combined with any runtime AI call it is a near-certain Lane 2.",
    mapsTo: "logic-yellow",
    effect: "raises-tier",
    confidence: "moderate",
    patterns: ["embeddings?|embedding\\b", "vector(Store|DB|Search)?", "pinecone|weaviate|chromadb|chroma|qdrant|faiss|pgvector", "similaritySearch|cosineSimilarity|retriev(e|al|er)|RetrievalQA|\\bRAG\\b", "(answer|ask)\\w*\\(\\s*question|chat\\s*over\\s*(docs|documents|pdf)"],
  },
  {
    id: "logic-probabilistic-summarize-draft",
    label: "Drafting / summarizing / generation, client-facing (YELLOW-RED)",
    why: "Common-patterns guide: drafting/summarizing is YELLOW-RED and Lane 2/Register because output is client-facing (disclosure applies) and relied on. Raises the tier and limits hosting; a strong Lane 2 signal when combined with any runtime AI call.",
    mapsTo: "logic-yellow",
    effect: "raises-tier",
    confidence: "moderate",
    patterns: ["summari[sz]e", "draft\\w*\\((Email|Letter|Memo|Response|Report)?", "generate\\w*(Text|Email|Draft|Report|Summary|Content|Memo|Letter|Narrative)", "rewrite|paraphrase|compose", "\\.generate\\(|messages\\.create\\(|chat\\.completions\\.create\\(", "(write|compose)\\s+(a|an|the)\\s+(email|memo|summary|letter|response)"],
  },
  {
    id: "logic-probabilistic-ml-inference",
    label: "In-browser / local ML model inference or scoring (YELLOW)",
    why: "STAR 3.2: probabilistic/judgment logic is YELLOW regardless of whether the model is hosted by a vendor. Local ML inference (onnxruntime/tfjs/transformers.js) or classify/score/predict pipelines produce probabilistic output; under 5.4 they need 100% human review, and relied-upon output raises the tier. Note: a LOCAL/in-browser model is NOT a 5.5 runtime AI *network* call, so it does not by itself fail 5.5 \u2014 but it is still YELLOW logic for 5.4 purposes.",
    mapsTo: "logic-yellow",
    effect: "raises-tier",
    confidence: "moderate",
    patterns: ["onnxruntime|onnxruntime-web", "@tensorflow/tfjs|tensorflow", "@xenova/transformers|pipeline\\(", "(classif|sentiment|predict|score)\\w*\\("],
  },
  {
    id: "numeric-mutation-downstream",
    label: "Formatting that changes numeric values used downstream",
    why: "Common-patterns guide: data-formatting is GREEN/Lane 1 BUT escalates if it changes numeric values used downstream (the value feeds something relied upon). Concrete arithmetic/rounding/scaling on parsed financial figures that then flows into an export or written output is the escalation marker; downstream reliance is user-confirmed.",
    mapsTo: "logic-yellow",
    effect: "context-needed",
    confidence: "weak",
    patterns: ["Math\\.(round|floor|ceil)\\(", "\\*\\s*100|/\\s*100", "toFixed\\(", "parseFloat\\([^)]*\\)\\s*[*/+\\-]", "\\b(currency|amount|balance|total|nav|price)\\b\\s*="],
  },
  {
    id: "logic-deterministic-green",
    label: "Deterministic, rule-based logic (data entry / formatting / rule-based validation)",
    why: "Common-patterns guide: data entry, data formatting, and rule-based validation are GREEN and Lane-1-eligible \u2014 the baseline that PASSES 5.4 absent any disqualifier. NOTE: GREEN != correct (rules are validated once then monitored); the analyzer scores posture for lane purposes only and must not claim correctness. Escalates only via numeric-mutation-downstream or a source-of-truth write.",
    mapsTo: "logic-green",
    effect: "informational",
    confidence: "moderate",
    patterns: ["addEventListener\\(\\s*['\"](submit|input|change)", "toFixed\\(|Intl\\.NumberFormat|toLocaleString\\(|date-fns|dayjs", "\\.replace\\(|parseFloat|parseInt|sortBy|filter\\(", "validate\\w*\\(|\\.test\\(\\s*/|zod|yup|joi"],
  },
  {
    id: "static-frontend-only",
    label: "Pure static client-side utility (no backend, no AI, no writes, no external net)",
    why: "When NONE of the disqualifying signals fire (no runtime AI / only the approved proxy, no backend, no source-of-truth write, no un-allowlisted external scripts/outbound calls, no sensitive persistence) AND logic is deterministic, the utility can satisfy all of Section 5 and is LANE 1 ELIGIBLE \u2014 subject to tier == USE and General-data confirmation. Precedence reminder: even a single static file goes to Lane 2 if the tier is APPROVE.",
    mapsTo: "5.1",
    effect: "informational",
    confidence: "moderate",
    patterns: ["(^|/)index\\.html$", "vite\\.config\\.(ts|js)|\"build\"\\s*:\\s*\"vite build\"", "createRoot\\(|ReactDOM\\.render", "staticwebapp\\.config\\.json$"],
  },
  {
    id: "build-tool-ai-attribution",
    label: "AI build-tool attribution (e.g. Lovable / Claude / v0 / gpt-engineer)",
    why: "KEY PRINCIPLE: the AI tool used to BUILD a utility does NOT determine its lane \u2014 only the STAR lane assignment derived from the running utility's behavior does. This signal is recorded as metadata ONLY and must NEVER affect tier or lane. Also covers 'openai'/'langchain' appearing only in build scripts, devDependencies, README/docs, or node_modules \u2014 not shipped runtime.",
    mapsTo: "pattern-classification",
    effect: "informational",
    confidence: "moderate",
    patterns: ["Generated with .*Claude Code", "lovable", "gpt-engineer", "Built with .*v0", "<meta[^>]*name=['\"]generator['\"]"],
  },
  {
    id: "approve-state-precedence",
    label: "Meta: any Approve-state trigger detected (tier-wins override)",
    why: "THE TIER ALWAYS WINS: an Approve-state utility goes to Lane 2 even if it is a single static file meeting every other condition, and additionally requires a Controlled Workflow Packet + AI Committee approval before go-live (Isolated Hosting). This meta-signal collects the Approve triggers and, once resolved true (after user confirmation of the context-needed dimensions), short-circuits to Lane 2.",
    mapsTo: "risk-tier-approve",
    effect: "forces-approve-state",
    confidence: "strong",
    patterns: ["(derived from: data-scope-restricted-keywords)", "(derived from: db-source-of-truth-write)", "(derived from: backend-as-a-service-write)", "(derived from: reliance-deliverable-markers)"],
  },
];
